// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEHWn31o5UhBw87ZwLXujH-aS_NcgjNg0',
    appId: '1:591799144347:web:f9a036df7b1fd05c2bdb3e',
    messagingSenderId: '591799144347',
    projectId: 'chakulaconnect',
    authDomain: 'chakulaconnect.firebaseapp.com',
    storageBucket: 'chakulaconnect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBh0NTt3Wwy4Z9-m16Jx9pKmK3eprNnJY',
    appId: '1:591799144347:android:ad168b76f6f700452bdb3e',
    messagingSenderId: '591799144347',
    projectId: 'chakulaconnect',
    storageBucket: 'chakulaconnect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuCJ9R9501k2ozbUnbr0C2-oHU9uZ25Yc',
    appId: '1:591799144347:ios:3c75350773549b1c2bdb3e',
    messagingSenderId: '591799144347',
    projectId: 'chakulaconnect',
    storageBucket: 'chakulaconnect.firebasestorage.app',
    iosBundleId: 'com.example.chakulaConnect',
  );
}
